name: LinkedIn Auto Apply Bot

on:
  schedule:
    - cron: "0 9 * * *"   # runs every day at 9 AM UTC (~2 PM Pakistan time)
  workflow_dispatch:      # allows manual run

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install playwright
          playwright install chromium

      - name: Run LinkedIn Auto Apply Bot
        env:
          LINKEDIN_EMAIL: ${{ secrets.LINKEDIN_EMAIL }}
          LINKEDIN_PASSWORD: ${{ secrets.LINKEDIN_PASSWORD }}
          RESUME_PATH: ${{ secrets.RESUME_PATH }}
          JOB_LOCATION: "Pakistan"
          JOBS_PER_CATEGORY: "10"
        run: python auto_apply.py
